### ISSUE TITLE
Need Tx Details, too.

### ISSUE THREAD

**Issue by WYYSXF** [ragestack/blockchain-parser#11]

**Comment by WYYSXF** [comment]
How can I get the Tx details, such as input addresses, output address, amount......

**Comment by ragestack** [comment]
There is no "Input address" or "Output address" in blockchain. There are the "scripts" - "input script" and "output script". The amount you looking for is the the string with name "Value = XXXXXXXXXXXXXXXX" where "XX.." is the 8 bytes hex representative of value for each output of any transaction.
