### ISSUE TITLE
Bug in read_varint

### ISSUE THREAD

**Issue by AlexeyBarsuk** [ragestack/blockchain-parser#13]
![Снимок экрана 2020-04-11 в 15 36 29](https://user-images.githubusercontent.com/26286722/79043890-bff14a00-7c0a-11ea-8abc-b92807c92eea.png)

**Comment by AlexeyBarsuk** [comment]
The most interesting thing is the bug in code does not affect the whole process of reading )

**Comment by ragestack** [comment]
Thanks! Fixed.
