### ISSUE TITLE
Syntax error in file name, folder name, or volume label

### ISSUE THREAD

**Issue by madeonukraine** [ragestack/blockchain-parser#15]
Hello Denis, indicated the saving of the blockchain to disk D, indicated this path in the software -
dirA = 'D:\BTC\blocks' # Directory where blk*.dat files are stored
#dirA = sys.argv[1]
dirB = 'D:\Result' # Directory where to save parsing results
#dirA = sys.argv[2]

here is the error code -
D: \Result\blockchain-parser-master> py blockchain-parser.py
Traceback (most recent call last):
   File "D:\Result\blockchain-parser-master\blockchain-parser.py", line 61, in <module>
     fList = os.listdir (dirA)
OSError: [WinError 123] Syntax error in file name, folder name or volume label: 'D: \\ BTC \ x08locks'

tried to write another way
   dirA = 'D:\BTC\blocks\' # Directory where blk * .dat files are stored
#dirA = sys.argv [1]
dirB = 'D:\Result\' # Directory where to save parsing results
#dirA = sys.argv [2]

then the mistake is
D:\Result\blockchain-parser-master> py blockchain-parser.py
   File "D:\Result\ blockchain-parser-master \ blockchain-parser.py", line 56
     dirA = 'D:\BTC\blocks\' # Directory where blk * .dat files are stored
                                                                        ^
SyntaxError: EOL while scanning string literal

I tried to run from the root of the C drive and put the blk * file next to it and indicate the path, the error repeats

Tell me what I'm doing wrong, thanks in advance

**Comment by ragestack** [comment]
Hi!
Try to use / in paths, not \
