### ISSUE TITLE
Could it parse out the specific details of the transaction

### ISSUE THREAD

**Issue by WYYSXF** [ragestack/blockchain-parser#16]

**Comment by WYYSXF** [comment]
For example, parse the input addresses and output addresses of the transaction

**Comment by ragestack** [comment]
You mean parsing the "Input script" and "Output script" details?

**Comment by ragestack** [comment]
May be sometime.

**Comment by WYYSXF** [comment]
yes!



---Original---

**Comment by WYYSXF** [comment]
Thank you very much. Could you tell me&nbsp;about how long it may take?



---Original---

**Comment by ragestack** [comment]
It depends on my free time

**Comment by WYYSXF** [comment]
Thank you very much



---Original---
