### ISSUE TITLE
get list of all adresses on bitcoin block chain

### ISSUE THREAD

**Issue by mohammadAsadolahi** [ragestack/blockchain-parser#18]
how can i get all addresses on bitcoin blockchain i mean every address that comited a transaction on blockchain no matter it has balance or not?
for example get list of all addresses in text file
no balance or transaction or anything else just adresses
thank you

**Comment by ragestack** [comment]
Hi! Just leave output script at the output data, the output script contains the address.

**Comment by mohammadAsadolahi** [comment]
i dont understand what you mean can you give me a example code please
i want to get all adresses that has any kind of transaction on blockchain of all time

**Comment by mohammadAsadolahi** [comment]
hello i emailed you and i would be so thanksful  if you answer me. thank you

**Comment by ragestack** [comment]
Line 218 of parser's code save output script to the resulting output file, this strings contains the address that you want to extract

**Comment by mohammadAsadolahi** [comment]
**hi and thank you for answering. i used your code and it works fine i get output file  but my problem is the "output and input script"  in result that you have mentioned does not have a bitcoin valid address. for example they are in 51 and 31 and 32 length but i downloaded positive balance addresses  from https://gz.blockchair.com/bitcoin/addresses/ and all addresses are 34 character long witch can be searched in blockchain sites to track their activities
problem with  https://blockchair.com file is it contains only positive balance addresses for today but i need all addresses had any activity from start of bitcoin

> for example these are some address from  https://gz.blockchair.com file:

1. 34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo
2. 38UmuUqPCrFmQo4khkomQwZ4VbY2nZMJ67
3. 1FeexV6bAHb8ybZjqQMjJrcCrHGW9sb6uF
4. 3LYJfcfHPXYJreMsASk2jkn69LWEYKzexb
5. 3Kzh9qAqVWQhEsfQz7zEQL1EuSx5tyNLNS
6. 3LQeSjqS5aXJVCDGSHPR88QvjheTwrhP8N
7. 1LdRcdxfbSnmCYYNdeYpUnztiYzVfBEQeC
8. 1AC4fMwgY8j9onSbXEWeH6Zan8QGMSdmtA



> and here is some lines of blockchain  parser output witch contains strange addresses:


TX version number = 00000001
Inputs count = 01
TX from hash = 0000000000000000000000000000000000000000000000000000000000000000
N output = FFFFFFFF
Input script = 04F3254A4D0107062F503253482F
Sequence number = FFFFFFFF
Outputs count = 1
Value = 000000012A05F200
Output script = 2102554C25F06B4A5E813F36F7C8B273BBF65937C6DB934B4C219F453DC5A58D7D9DAC
Lock time = 00000000
TX hash = 9BA72F637B19CCAC0EA9F79BB100800869BDD35264647EEC9B2F68ACA47F5696


TX version number = 00000001
Inputs count = 01
TX from hash = 0000000000000000000000000000000000000000000000000000000000000000
N output = FFFFFFFF
Input script = 04FFFF001D0104455468652054696D65732030332F4A616E2F32303039204368616E63656C6C6F72206F6E206272696E6B206F66207365636F6E64206261696C6F757420666F722062616E6B73
Sequence number = FFFFFFFF
Outputs count = 1
Value = 000000012A05F200
Output script = 4104678AFDB0FE5548271967F1A67130B7105CD6A828E03909A67962E0EA1F61DEB649F6BC3F4CEF38C4F35504E51EC112DE5C384DF7BA0B8D578A4C702B6BF11D5FAC
Lock time = 00000000
TX hash = 4A5E1E4BAAB89F3A32518A88C31BC87F618F76673E2CC77AB2127B7AFDEDA33B**

**Comment by ragestack** [comment]
Output script = 4104678AFDB0FE5548271967F1A67130B7105CD6A828E03909A67962E0EA1F61DEB649F6BC3F4CEF38C4F35504E51EC112DE5C384DF7BA0B8D578A4C702B6BF11D5FAC

this script is an uncompressed public key that is one of the form of address representation https://en.bitcoin.it/wiki/Script

**Comment by mohammadAsadolahi** [comment]
there are many transaction without addresses. what do you think to get every address from blockchain i just need compressed 34 character addresses. i can get transaction count of an address from sites if the transaction is >0 its on block chain and if it 0 it is not but api's will block you for too many reqs. and i think create a file of compressed address and binary search on it to check if its on block chain or not. but my main problem is that i don't know how to extract all addresses from bitcoin blockchain into a single file

**Comment by mohammadAsadolahi** [comment]
if there will be uncompressed addresses too its ok but many transaction's has no address after running the parser on it

**Comment by ragestack** [comment]
you should read theory first, i can not explain you all in this issue thread

**Comment by huynh922** [comment]
....
