### ISSUE TITLE
How to find reused r value from btc tx

### ISSUE THREAD

**Issue by Ango87** [ragestack/blockchain-parser#20]
I have two transactions for a bitcoin address when I want to extract the value of r I notice they are different, what should I do

**Comment by ragestack** [comment]
hi
you may extract all r values from any blk*.dat file you want, so then you can find duplicates in those list (lists). this parser works well if you want to make a complex research of blockchain data, not for the only one transaction but for a big data.

**Comment by Ango87** [comment]
@ragestack Thank you for this explanation, can you please tell me how to get the R value from this file, I mean what code should I use, I am new to the field, I am looking forward to your help with this

**Comment by ragestack** [comment]
you need to leave input script lines for output (code line #168), then you can cut scripts by yourself for leaving R and so on
