### ISSUE TITLE
TX

### ISSUE THREAD

**Issue by kpot87** [ragestack/blockchain-parser#23]
hi! would like to ask its possible to modify script to received rawtx? ScriptSig Size and ScriptPubKey Size must be calculated separately or its just didnt parse? thank for your work!

**Comment by ragestack** [comment]
Signature and PubKey are in InputScript field. It is possible to parse InputScript field and extract signatures and keys, but I didn't do that, it's not so hard to modify my script by yourself.

**Comment by kpot87** [comment]
> Signature and PubKey are in InputScript field. It is possible to parse InputScript field and extract signatures and keys, but I didn't do that, it's not so hard to modify my script by yourself.

Извини за наглость, а ты не мог бы вывести RawTX в отдельную строку, что бы сохраняло? Спасибо

**Comment by ragestack** [comment]
> > Signature and PubKey are in InputScript field. It is possible to parse InputScript field and extract signatures and keys, but I didn't do that, it's not so hard to modify my script by yourself.
> 
> 
> 
> Извини за наглость, а ты не мог бы вывести RawTX в отдельную строку, что бы сохраняло? Спасибо

Мог бы, но это не бесплатно
