### ISSUE TITLE
crashes on first block

### ISSUE THREAD

**Issue by Giszmo** [ragestack/blockchain-parser#3]
Toying around with blockchain parsers I also tried yours ... to little success so far. I added just a print line before the crashing line and set my blockchain data folder.

```
$ python blockchainParser.py 
Start /home/leo/.bitcoin/blocks/blk00000.dat in 2019-03-21 22:22:55.012799
txCount is 1
txCount is 115231992590434559
Traceback (most recent call last):
  File "blockchainParser.py", line 146, in <module>
    for k in range(txCount):
MemoryError
```

**Comment by normanvolt** [comment]
Can you share your's blk00000.dat file here?
If parser crashing, the reason is that input blk*.dat file was not fully downloaded, or there is data corruption in blockchain data file.
