### ISSUE TITLE
Need Tx Details

### ISSUE THREAD

**Issue by FeloAngel** [ragestack/blockchain-parser#5]
This parser works great, however the ouput does not have the transaction addresses and BTC quantity explicitly. How do I decode that information?

Appreciate your help.

This is what I see as output:

_transactionVersionNumber = 00000001
Inputs count = 02
TX from hash = 4E94BFC9654465092E38279FE94FBB5249FC4D07F2544960BC8A31DD1469DB9E
N output = 00000002
Input script = 0047304402202C83593385F29E32FA7E18FFB26F49FABE1BC6533F958AB04B6206F07DB247FC0220240E687974432FB912AF0D4EBEF780E6A3FC627E272FD653C9EC6E3B999F860901473044022038B2DD1C910A775C170B90D7AB22926F3E8912E3FFDDBC8CFB67F04C4C1B911E0220553ABF9429655747ED902A0D99E12E8596AA80028AF95B1DCB32E4C237A65E49014C69522103F51E8076324E1E6AE665CCC645D1E0DD3998236DF5F6263140BFC40448C81FAB2102A03CD673CE078E6F6922793B4067B3EDA0BD79C4CA41C961099DA66AC7F1108E2102FD7D8158C3AF6E11EB0C13859FD0A963ED86D955BB89CF7D94EFD720226C7BA853AE
sequenceNumber = FFFFFFFF
TX from hash = 9263840FC4B9DA86A8A606AF82268F9EBC7D4D8375CD395895CFA3E26171C6E0
N output = 00000000
Input script = 00483045022100E48A1692D82C6245BE690FC5C038B8390DF6F0FDB3460FE9B2F7ECCC7EFAB3BC022037A8538B5D4710A3EE0EA87590AB7E97F113CB107DFF9B16B9E586A80E3CB3650147304402204DFF76D443C72554818962F3B19E24A4112CD8C0C38559B09A941160BDC06F0902202F5D86529E9965D767C182947934CFF78C5CB490D9CFF2E9C955C65B6ADF7F39014C6952210245D5CF280B76327A059158537DA5D596365130A234769CD2EE4F1B88A2BA24522102FD08476944A2B7B67CEB870249C435532080A4E34D5DB06420674E9E10F9653721034A06FE8F3129EC4CDB849B3BC52C6EA2F4C119FA1D0DAFA3DCAF478BA58EB9BB53AE
sequenceNumber = FFFFFFFF
Outputs count = 2
Value = 0000000000C5CE1F
Output script = A9142A25F5F255EB0F7DAF1A96464E63E7A46DF1A3EC87
Value = 0000000000000000
Output script = 6A146F6D6E69000000000000001F00000004A817C800
Lock time = 00000000
TX hash = E6B4E3A9925C6C2D099BB6DDFD4F2A65575F8ACE66E7E9E731FEEB19C9A85DC4_

**Comment by FeloAngel** [comment]
Is that information stored in the TX Hash?
Example:
TX hash = E6B4E3A9925C6C2D099BB6DDFD4F2A65575F8ACE66E7E9E731FEEB19C9A85DC4 

Would contain the addresses and amount?, if not, what should I do to get that information?

**Comment by ragestack** [comment]
There is no "address" in blockchain. There are the "scripts" - "input script" and "output script". The amount you looking for is the the string with name "Value = XXXXXXXXXXXXXXXX" where "XX.." is the 8 bytes hex representative of value for each output of any transaction.
